### ISSUE TITLE
2.0.0 fails to build with googletest 1.17.0

### ISSUE THREAD

**Issue by gdt** [libspatialindex/libspatialindex#300]
tl;dr  Build fails with googletest apparently due to C++ version issues.   Is this working for anyone?

Trying to build 2.0.0 (because of #277), I got build failures.   I noticed that libspatialindex says c++11, but pkgsrc's googletest package is coded for c++14.  So I switched the spatilalindex build to requiring a compiler capable of c++14.
```
/tmp/work/geography/spatialindex/work/.buildlink/include/gtest/internal/gtest-port.h:273:2: error: #error C++ versions less than C++17 are not supported.
  273 | #error C++ versions less than C++17 are not supported.
```

Switching the requirement to a compiler capable of c++17 resulted in no change, I am speculating because libspatalite (quite reasonably) sets the build flags to --std=c++11.

Patching CMakeLists.txt to check for c++17 instead gets further, even though apparently there is no --std on the build line.

```
[98/98] Linking CXX executable bin/libsidxtest
FAILED: [code=1] bin/libsidxtest 
: && /tmp/work/geography/spatialindex/work/.cwrapper/bin/c++ -O2 -I/usr/pkg/include -DNDEBUG -Wl,-zrelro -L/usr/pkg/lib -Wl,-R/usr/pkg/lib test/gtest/CMakeFiles/libsidxtest.dir/main.cc.o -o bin/libsidxtest  src/libspatialindex_c.so.7.0.0  lib/libgtest.so.1.14.0  src/libspatialindex.so.7.0.0  -lpthread && :
ld: test/gtest/CMakeFiles/libsidxtest.dir/main.cc.o: in function `__static_initialization_and_destruction_0(int, int) [clone .constprop.0]':
main.cc:(.text.startup+0x1ed): undefined reference to `testing::internal::MakeAndRegisterTestInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
ld: main.cc:(.text.startup+0x2bf): undefined reference to `testing::internal::MakeAndRegisterTestInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
ld: main.cc:(.text.startup+0x391): undefined reference to `testing::internal::MakeAndRegisterTestInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
ld: main.cc:(.text.startup+0x463): undefined reference to `testing::internal::MakeAndRegisterTestInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
ld: main.cc:(.text.startup+0x535): undefined reference to `testing::internal::MakeAndRegisterTestInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
ld: test/gtest/CMakeFiles/libsidxtest.dir/main.cc.o:main.cc:(.text.startup+0x607): more undefined references to `testing::internal::MakeAndRegisterTestInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' follow
ninja: build stopped: subcommand failed.
*** Error code 1
```

**Comment by pangwangshu** [comment]
I opened #304 for this.

The root cause turned out to be that `test/gtest/CMakeLists.txt` linked the bare name `gtest` rather than the imported target. With `-DSYSTEM_GTEST=ON` that name goes straight to the linker as `-lgtest`, so none of the external GoogleTest's usage requirements are applied — neither its include directories (which is how 1.17 headers end up paired with a 1.14 library, giving the `MakeAndRegisterTestInfo` undefined references) nor the `cxx_std_17` it has required since 1.15, hence the `#error C++ versions less than C++17` you hit.

The PR links `GTest::gtest`, which lets CMake raise the standard for the test target alone; the library still builds as C++11. Verified against GoogleTest 1.18: `SYSTEM_GTEST=ON` fails to build on `main` today and passes with the patch, shared and static, with the bundled build unaffected. I also added a CI job for `SYSTEM_GTEST=ON`, since nothing covered that path.

@hobu would you mind taking a look when you have a moment?
